author: Aaron Sutton
author_url: https://github.com/aaronjsutton
copyright: "Copyright © 2018 Aaron Sutton. All Rights Reserved."

module: DirectionalPad
github_url: https://github.com/aaronjsutton/DirectionalPad
sdk: iphone


